using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Test1 : MonoBehaviour
{   public float moveSpeed;
    public float rotSpeed;
    public float jumpForce;
    public float jumpCD;
    public float score;

    public Rigidbody rigidBody;
    // Start is called before the first frame update
    void Start()
    {
        rigidBody = GetComponent<Rigidbody>();
    }

    // Update is called once per frame
    void Update()
    {
        float translation = Input.GetAxis("Vertical") * moveSpeed;
        float rotation = Input.GetAxis("Horizontal") * rotSpeed;

        translation *= Time.deltaTime;
        rotation *= Time.deltaTime;

        transform.Translate(0,0, translation);
        transform.Rotate(0,rotation,0);    

        if (Input.GetButton("Jump"))
        {
            rigidBody.AddForce(new Vector3(0,jumpForce,0),ForceMode.Impulse);
        }
    }
}
